# web server
nginx:
  #image: nginx:latest
  build: ./nginx
  ports:
    - "80:80"
    # - "443:443"
  volumes:
    # app
    - ./app/src:/usr/share/nginx/html
    - ./app/php56:/usr/share/nginx/php56html
    #- /media/zhangdayu/2c4662db-bc41-44a8-a051-762860deb7da/dy/data/www:/usr/share/nginx/php56html
    # nginx configs
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    # certificates
    #- ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
    #- ./nginx/ca/server.key/:/etc/nginx/server.key:ro
  links:
    - fpm:__DOCKER_PHP_FPM__
    - php56-fpm:fpm56
  extra_hosts:
    - esb.test:10.10.112.195

# php-fpm
fpm:
  build: ./php-fpm
  ports:
    - "9000"
  working_dir: /usr/share/nginx/html
  volumes:
    - ./app/src:/usr/share/nginx/html
    # Your php.ini
    - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
  environment:
    - REDIS_HOST=10.10.112.1
    - DB_CR_CENTER_HOST=10.10.112.236
    - DB_CR_CENTER_DB=cr_center
    - DB_CR_CEMTER_USER=root
    - DB_CR_CEMTER_PASSWD=111222
    - DB_MBGCENTER_HOST=10.10.112.236
    - DB_MBGCENTER_DB=mbgCenter
    - DB_MBGCEMTER_USER=root
    - DB_MBGCEMTER_PASSWD=111222
    - DB_APICLUSTER_HOST=10.10.112.236
    - DB_APICLUSTER_DB=api_cluster
    - DB_APICLUSTER_USER=root
    - DB_APICLUSTER_PASSWD=111222

    - CLOUD_PLATFORM_HOST=10.10.112.195
    - CLOUD_PLATFORM_DB=cloud_platform
    - CLOUD_PLATFORM_USER=root
    - CLOUD_PLATFORM_PASSWD=111222
    #rabbitmq
    - RABBITMQ_HOST=10.10.107.22
    - RABBITMQ_PORT=5672
    - RABBITMQ_USER=guest
    - RABBITMQ_PASSWD=guest
  links:
    - mysql:mysql
# php56-fpm
php56-fpm:
   build: ./php56-fpm
   ports:
     - "9000"
   volumes: 
     - ./app/php56:/usr/share/nginx/php56html
     #- /media/zhangdayu/2c4662db-bc41-44a8-a051-762860deb7da/dy/data/www:/usr/share/nginx/html
     - ./php56-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
   links:
     - mysql:mysql
   extra_hosts:
     - esb.test:10.10.112.195
# database
mysql:
  image: daocloud.io/library/mysql:latest
  ports:
    # Allow client to access 3306
    - "3306:3306"
  volumes:
    # NOTE: your data will be stored in ./mysql
    - ./mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=123456
